stages:
  - build

# Build Docker image
docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: registry.gitlab.com
    DOCKER_IMAGE: ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
    DOCKER_TAG: latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - export LOWERCASE_IMAGE=$(echo "$DOCKER_IMAGE" | tr '[:upper:]' '[:lower:]')
    - cd webrtc-app  # ย้ายไปยังไดเรกทอรีที่มี Dockerfile
    - docker build -t $LOWERCASE_IMAGE:$DOCKER_TAG .
    - docker push $LOWERCASE_IMAGE:$DOCKER_TAG
  only:
    - branches
