# Use the official Node.js image as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package.json ./

# Install dependencies
RUN npm install express socket.io

# Copy the entire application code to the working directory
COPY . .

# Expose the port the server will run on
EXPOSE 3000

# Set environment variables (optional, adjust as needed)
ENV NODE_ENV=production

# Start the application
CMD ["node", "server/server.js"]
